In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_california_housing
df = fetch_california_housing()

In [ ]:
dataset = pd.DataFrame(df.data)


In [ ]:

california_housing = fetch_california_housing()


feature_names = california_housing.feature_names
data = california_housing.data


df = pd.DataFrame(data, columns=feature_names)

print(df.head())

   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25  


In [ ]:
X = data
Y= california_housing.target

In [ ]:
Y


array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(  X, Y, test_size=0.30, random_state=42)


In [ ]:
X_train

array([[   4.1312    ,   35.        ,    5.88235294, ...,    2.98529412,
          33.93      , -118.02      ],
       [   2.8631    ,   20.        ,    4.40120968, ...,    2.0141129 ,
          32.79      , -117.09      ],
       [   4.2026    ,   24.        ,    5.61754386, ...,    2.56491228,
          34.59      , -120.14      ],
       ...,
       [   2.9344    ,   36.        ,    3.98671727, ...,    3.33206831,
          34.03      , -118.38      ],
       [   5.7192    ,   15.        ,    6.39534884, ...,    3.17889088,
          37.58      , -121.96      ],
       [   2.5755    ,   52.        ,    3.40257649, ...,    2.10869565,
          37.77      , -122.42      ]])

In [ ]:
Y_train

array([1.938, 1.697, 2.598, ..., 2.221, 2.835, 3.25 ])

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
scaler = StandardScaler()

In [ ]:
X_train=scaler.fit_transform(X_train)

In [ ]:
X_test=scaler. transform(X_test)

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
regression=LinearRegression ()
regression.fit(X_train,Y_train)

LinearRegression()

In [ ]:
mse=cross_val_score (regression,X_train,Y_train,scoring='neg_mean_squared_error' ,cv =20 )

In [ ]:
np.mean(mse)

-0.5256310821763283

In [ ]:
reg_pred=regression.predict(X_test)

In [ ]:
reg_pred

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
score=r2_score(reg_pred,Y_test)

In [ ]:
score

0.34513393809439674